/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gauthier_matthieu.application;


import com.gauthier_matthieu.old.GestionDonnees;
import com.gauthier_matthieu.metier.Prospects;
import com.gauthier_matthieu.fonctions.MPanelPrinter;

import java.awt.*;
import com.gauthier_matthieu.entities.*;
import java.awt.print.Printable;
import javax.swing.*;
import java.io.*;
import java.text.DateFormat;
import java.util.*;



/**
 *
 * @author glantoine
 */
public class Consultation_Prospects extends javax.swing.JFrame {
    private DateFormat sdf =DateFormat.getDateInstance(DateFormat.SHORT,Locale.getDefault());
    private JTable tableau;
    private Gestion_Prospect gp;
    //transmition tableau dans constructeur
    public Consultation_Prospects(JTable tableau,Gestion_Prospect gp) {
        initComponents();
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("..//image//logo-02.png")));
        setLocationRelativeTo(null);
        this.tableau=tableau;
        this.gp=gp;
        
        Lb_NumeroProspect.setText("");
        Lb_Complement_Consult.setText("");
        Lb_DerniereVisite_Consult.setText("");
        Lb_Mail_Consult.setText("");
        Lb_NomContact_Consult.setText("");
        Lb_NumRue_Consult.setText("");
        Lb_Pays_Consult.setText("");
        Lb_RepresentantNomPrenom_Consult.setText("");
        Lb_PrenomContact_Consult.setText("");
        Lb_Rue_Consult.setText("");
        Lb_Siret_Consult.setText("");
        Lb_Societe_Consult.setText("");
        Lb_Telephone_Consult.setText("");
        Lb_Ville_Consult.setText("");
        Lb_codePostal_Consult.setText("");
        
        /*appel de la méthode Gestion Prospect*/
        GestionDonnees gd = new GestionDonnees();
        /*appel du hashMat client avec toute les fonctions*/
        HashMap<Integer,Prospects> prospect= gd.getProspects();
        /*Création d'un objet client à partir du hashMap, ce qui permet de stocker toute les donnée de la ligne*/
        Prospects prospectObjet = prospect.get(Integer.parseInt(tableau.getValueAt(tableau.getSelectedRow(), 0).toString()));
        Lb_NumeroProspect.setText(Integer.toString(prospectObjet.getNumeroProspect()));
        Lb_NomContact_Consult.setText(prospectObjet.getNom());
        Lb_PrenomContact_Consult.setText(prospectObjet.getPrenom());
        Lb_Societe_Consult.setText(prospectObjet.getNomEntreprise());
        Lb_Siret_Consult.setText(prospectObjet.getSiret());
        Lb_NumRue_Consult.setText(Integer.toString(prospectObjet.getNumeroVoie()));
        Lb_Rue_Consult.setText(prospectObjet.getAdresse());
        Lb_Complement_Consult.setText(prospectObjet.getComplementAdresse());
        Lb_Ville_Consult.setText(prospectObjet.getVille());
        Lb_codePostal_Consult.setText(prospectObjet.getCodePostal());
        Lb_Pays_Consult.setText(prospectObjet.getPays());
        Lb_Mail_Consult.setText(prospectObjet.getMail());
        Lb_Telephone_Consult.setText(prospectObjet.getNumerotel());
        Lb_DerniereVisite_Consult.setText(sdf.format(prospectObjet.getDerniereVisite()));
        String nomPrenomRepresentant[];
        nomPrenomRepresentant=gd.getRepresentants().get(prospectObjet.getNumeroRepresentant()).toString().split("\\.");
        Lb_RepresentantNomPrenom_Consult.setText(nomPrenomRepresentant[1]);
        //Lb_RepresentantNomPrenom_Consult.setText(Integer.toString(prospectObjet.getNumeroRepresentant()));
    }
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_ConsutationProspect = new javax.swing.JPanel();
        Lb_Fenetre = new javax.swing.JLabel();
        Bt_Annuler = new javax.swing.JButton();
        Bt_Aide = new javax.swing.JButton();
        Bt_Imprimer = new javax.swing.JButton();
        jPanel_Contact = new javax.swing.JPanel();
        Lb_NomContact = new javax.swing.JLabel();
        Lb_PrenomContact = new javax.swing.JLabel();
        Lb_Mail = new javax.swing.JLabel();
        Lb_Telephone = new javax.swing.JLabel();
        Lb_NomContact_Consult = new javax.swing.JLabel();
        Lb_PrenomContact_Consult = new javax.swing.JLabel();
        Lb_Telephone_Consult = new javax.swing.JLabel();
        Lb_Mail_Consult = new javax.swing.JLabel();
        jPanel_Adresse = new javax.swing.JPanel();
        Lb_Ville = new javax.swing.JLabel();
        Lb_CodePostal = new javax.swing.JLabel();
        Lb_Pays = new javax.swing.JLabel();
        Lb_Pays_Consult = new javax.swing.JLabel();
        Lb_Rue = new javax.swing.JLabel();
        Lb_NumRue = new javax.swing.JLabel();
        Lb_Complement = new javax.swing.JLabel();
        Lb_Rue_Consult = new javax.swing.JLabel();
        Lb_NumRue_Consult = new javax.swing.JLabel();
        Lb_codePostal_Consult = new javax.swing.JLabel();
        Lb_Complement_Consult = new javax.swing.JLabel();
        Lb_Ville_Consult = new javax.swing.JLabel();
        jPanel_Entreprise = new javax.swing.JPanel();
        Lb_Societe = new javax.swing.JLabel();
        Lb_Siret = new javax.swing.JLabel();
        Lb_Societe_Consult = new javax.swing.JLabel();
        Lb_Siret_Consult = new javax.swing.JLabel();
        jPanel_Entreprise2 = new javax.swing.JPanel();
        Lb_RepresentantNomPrenom = new javax.swing.JLabel();
        Lb_RepresentantNomPrenom_Consult = new javax.swing.JLabel();
        Lb_DerniereVisite = new javax.swing.JLabel();
        Lb_DerniereVisite_Consult = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        Lb_copyright = new java.awt.Label();
        Lb_NumeroProspect = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Consultation Prospect");
        setMinimumSize(new java.awt.Dimension(950, 530));
        setName("Consultation Clients"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel_ConsutationProspect.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_ConsutationProspect.setMaximumSize(new java.awt.Dimension(950, 530));
        jPanel_ConsutationProspect.setMinimumSize(new java.awt.Dimension(950, 530));
        jPanel_ConsutationProspect.setPreferredSize(new java.awt.Dimension(950, 530));

        Lb_Fenetre.setFont(new java.awt.Font("Gill Sans MT", 3, 30)); // NOI18N
        Lb_Fenetre.setForeground(new java.awt.Color(102, 102, 102));
        Lb_Fenetre.setText("CONSULTATION PROSPECT   n°");
        Lb_Fenetre.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        Bt_Annuler.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Bt_Annuler.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gauthier_matthieu/image/cross-circular-button.png"))); // NOI18N
        Bt_Annuler.setText("QUITTER");
        Bt_Annuler.setPreferredSize(new java.awt.Dimension(130, 25));
        Bt_Annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_AnnulerActionPerformed(evt);
            }
        });

        Bt_Aide.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Bt_Aide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gauthier_matthieu/image/question-mark.png"))); // NOI18N
        Bt_Aide.setText("AIDE");
        Bt_Aide.setPreferredSize(new java.awt.Dimension(130, 25));
        Bt_Aide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_AideActionPerformed(evt);
            }
        });

        Bt_Imprimer.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Bt_Imprimer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gauthier_matthieu/image/printer (1).png"))); // NOI18N
        Bt_Imprimer.setText("IMPRESSION");
        Bt_Imprimer.setToolTipText("");
        Bt_Imprimer.setPreferredSize(new java.awt.Dimension(130, 25));
        Bt_Imprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_ImprimerActionPerformed(evt);
            }
        });

        jPanel_Contact.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_Contact.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CONTACT", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Gill Sans MT Condensed", 2, 24), new java.awt.Color(102, 102, 102))); // NOI18N

        Lb_NomContact.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        Lb_NomContact.setForeground(new java.awt.Color(102, 102, 102));
        Lb_NomContact.setText("Nom :");

        Lb_PrenomContact.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        Lb_PrenomContact.setForeground(new java.awt.Color(102, 102, 102));
        Lb_PrenomContact.setText("Prénom :");

        Lb_Mail.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        Lb_Mail.setForeground(new java.awt.Color(102, 102, 102));
        Lb_Mail.setText("Mail :");

        Lb_Telephone.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        Lb_Telephone.setForeground(new java.awt.Color(102, 102, 102));
        Lb_Telephone.setText("Téléphone :");
        Lb_Telephone.setToolTipText("");

        Lb_NomContact_Consult.setFont(new java.awt.Font("Gill Sans MT", 2, 15)); // NOI18N
        Lb_NomContact_Consult.setText("zzzz");
        Lb_NomContact_Consult.setToolTipText("");

        Lb_PrenomContact_Consult.setFont(new java.awt.Font("Gill Sans MT", 2, 15)); // NOI18N
        Lb_PrenomContact_Consult.setText("zzzz");
        Lb_PrenomContact_Consult.setToolTipText("");

        Lb_Telephone_Consult.setFont(new java.awt.Font("Gill Sans MT", 2, 15)); // NOI18N
        Lb_Telephone_Consult.setText("zzzz");
        Lb_Telephone_Consult.setToolTipText("");

        Lb_Mail_Consult.setFont(new java.awt.Font("Gill Sans MT", 2, 15)); // NOI18N
        Lb_Mail_Consult.setText("zzzz");
        Lb_Mail_Consult.setToolTipText("");

        javax.swing.GroupLayout jPanel_ContactLayout = new javax.swing.GroupLayout(jPanel_Contact);
        jPanel_Contact.setLayout(jPanel_ContactLayout);
        jPanel_ContactLayout.setHorizontalGroup(
            jPanel_ContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ContactLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_ContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Lb_Mail)
                    .addComponent(Lb_Telephone)
                    .addComponent(Lb_NomContact)
                    .addComponent(Lb_PrenomContact))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_ContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Lb_NomContact_Consult, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lb_PrenomContact_Consult, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lb_Telephone_Consult, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lb_Mail_Consult, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel_ContactLayout.setVerticalGroup(
            jPanel_ContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ContactLayout.createSequentialGroup()
                .addGroup(jPanel_ContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lb_NomContact)
                    .addComponent(Lb_NomContact_Consult))
                .addGap(11, 11, 11)
                .addGroup(jPanel_ContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lb_PrenomContact)
                    .addComponent(Lb_PrenomContact_Consult))
                .addGap(11, 11, 11)
                .addGroup(jPanel_ContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lb_Telephone)
                    .addComponent(Lb_Telephone_Consult))
                .addGap(11, 11, 11)
                .addGroup(jPanel_ContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lb_Mail)
                    .addComponent(Lb_Mail_Consult)))
        );

        jPanel_Adresse.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_Adresse.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ADRESSE", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Gill Sans MT Condensed", 2, 24), new java.awt.Color(102, 102, 102))); // NOI18N

        Lb_Ville.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        Lb_Ville.setForeground(new java.awt.Color(102, 102, 102));
        Lb_Ville.setText("Ville :");

        Lb_CodePostal.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        Lb_CodePostal.setForeground(new java.awt.Color(102, 102, 102));
        Lb_CodePostal.setText("Code Postal :");

        Lb_Pays.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        Lb_Pays.setForeground(new java.awt.Color(102, 102, 102));
        Lb_Pays.setText("Pays :");

        Lb_Pays_Consult.setFont(new java.awt.Font("Gill Sans MT", 2, 15)); // NOI18N
        Lb_Pays_Consult.setText("zzzzz");

        Lb_Rue.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        Lb_Rue.setForeground(new java.awt.Color(102, 102, 102));
        Lb_Rue.setText("Adresse :");

        Lb_NumRue.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        Lb_NumRue.setForeground(new java.awt.Color(102, 102, 102));
        Lb_NumRue.setText("Numéro :");

        Lb_Complement.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        Lb_Complement.setForeground(new java.awt.Color(102, 102, 102));
        Lb_Complement.setText("Complement :");

        Lb_Rue_Consult.setFont(new java.awt.Font("Gill Sans MT", 2, 15)); // NOI18N
        Lb_Rue_Consult.setText("zzzz");

        Lb_NumRue_Consult.setFont(new java.awt.Font("Gill Sans MT", 2, 15)); // NOI18N
        Lb_NumRue_Consult.setText("zzzz");

        Lb_codePostal_Consult.setFont(new java.awt.Font("Gill Sans MT", 2, 15)); // NOI18N
        Lb_codePostal_Consult.setText("zzzz");

        Lb_Complement_Consult.setFont(new java.awt.Font("Gill Sans MT", 2, 15)); // NOI18N
        Lb_Complement_Consult.setText("zzzz");

        Lb_Ville_Consult.setFont(new java.awt.Font("Gill Sans MT", 2, 15)); // NOI18N
        Lb_Ville_Consult.setText("zzzz");

        javax.swing.GroupLayout jPanel_AdresseLayout = new javax.swing.GroupLayout(jPanel_Adresse);
        jPanel_Adresse.setLayout(jPanel_AdresseLayout);
        jPanel_AdresseLayout.setHorizontalGroup(
            jPanel_AdresseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_AdresseLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_AdresseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_AdresseLayout.createSequentialGroup()
                        .addComponent(Lb_Ville)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Lb_CodePostal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Lb_codePostal_Consult, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel_AdresseLayout.createSequentialGroup()
                        .addGroup(jPanel_AdresseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Lb_Complement)
                            .addComponent(Lb_NumRue))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel_AdresseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_AdresseLayout.createSequentialGroup()
                                .addComponent(Lb_NumRue_Consult, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Lb_Rue)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel_AdresseLayout.createSequentialGroup()
                                .addComponent(Lb_Complement_Consult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())))))
            .addGroup(jPanel_AdresseLayout.createSequentialGroup()
                .addGroup(jPanel_AdresseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_AdresseLayout.createSequentialGroup()
                        .addContainerGap(206, Short.MAX_VALUE)
                        .addComponent(Lb_Rue_Consult, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_AdresseLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(Lb_Pays)
                        .addGap(58, 58, 58)
                        .addGroup(jPanel_AdresseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Lb_Pays_Consult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel_AdresseLayout.createSequentialGroup()
                                .addComponent(Lb_Ville_Consult, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel_AdresseLayout.setVerticalGroup(
            jPanel_AdresseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_AdresseLayout.createSequentialGroup()
                .addGroup(jPanel_AdresseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lb_NumRue)
                    .addComponent(Lb_NumRue_Consult)
                    .addComponent(Lb_Rue)
                    .addComponent(Lb_Rue_Consult))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_AdresseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Lb_Complement_Consult)
                    .addComponent(Lb_Complement))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_AdresseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_AdresseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Lb_Ville_Consult)
                        .addComponent(Lb_CodePostal)
                        .addComponent(Lb_codePostal_Consult))
                    .addComponent(Lb_Ville))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_AdresseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lb_Pays)
                    .addComponent(Lb_Pays_Consult, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel_Entreprise.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_Entreprise.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ENTREPRISE", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Gill Sans MT Condensed", 2, 24), new java.awt.Color(102, 102, 102))); // NOI18N
        jPanel_Entreprise.setPreferredSize(new java.awt.Dimension(114, 111));

        Lb_Societe.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        Lb_Societe.setForeground(new java.awt.Color(102, 102, 102));
        Lb_Societe.setText("Société : ");

        Lb_Siret.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        Lb_Siret.setForeground(new java.awt.Color(102, 102, 102));
        Lb_Siret.setText("Siret : ");

        Lb_Societe_Consult.setFont(new java.awt.Font("Gill Sans MT", 2, 15)); // NOI18N
        Lb_Societe_Consult.setText("zzz");

        Lb_Siret_Consult.setFont(new java.awt.Font("Gill Sans MT", 2, 15)); // NOI18N
        Lb_Siret_Consult.setText("zzzzz");

        javax.swing.GroupLayout jPanel_EntrepriseLayout = new javax.swing.GroupLayout(jPanel_Entreprise);
        jPanel_Entreprise.setLayout(jPanel_EntrepriseLayout);
        jPanel_EntrepriseLayout.setHorizontalGroup(
            jPanel_EntrepriseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_EntrepriseLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_EntrepriseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Lb_Societe)
                    .addComponent(Lb_Siret))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_EntrepriseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Lb_Societe_Consult, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Lb_Siret_Consult, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel_EntrepriseLayout.setVerticalGroup(
            jPanel_EntrepriseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_EntrepriseLayout.createSequentialGroup()
                .addGroup(jPanel_EntrepriseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lb_Societe)
                    .addComponent(Lb_Societe_Consult))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_EntrepriseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lb_Siret)
                    .addComponent(Lb_Siret_Consult))
                .addGap(12, 12, 12))
        );

        jPanel_Entreprise2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_Entreprise2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "REPRESENTANT", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Gill Sans MT Condensed", 2, 24), new java.awt.Color(102, 102, 102))); // NOI18N

        Lb_RepresentantNomPrenom.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        Lb_RepresentantNomPrenom.setForeground(new java.awt.Color(102, 102, 102));
        Lb_RepresentantNomPrenom.setText("Nom, Prénom :");

        Lb_RepresentantNomPrenom_Consult.setFont(new java.awt.Font("Gill Sans MT", 2, 15)); // NOI18N
        Lb_RepresentantNomPrenom_Consult.setText("zzzzz");

        Lb_DerniereVisite.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        Lb_DerniereVisite.setForeground(new java.awt.Color(102, 102, 102));
        Lb_DerniereVisite.setText("Dernière visite:");

        Lb_DerniereVisite_Consult.setFont(new java.awt.Font("Gill Sans MT", 2, 15)); // NOI18N
        Lb_DerniereVisite_Consult.setText("zzzzz");

        javax.swing.GroupLayout jPanel_Entreprise2Layout = new javax.swing.GroupLayout(jPanel_Entreprise2);
        jPanel_Entreprise2.setLayout(jPanel_Entreprise2Layout);
        jPanel_Entreprise2Layout.setHorizontalGroup(
            jPanel_Entreprise2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Entreprise2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel_Entreprise2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_Entreprise2Layout.createSequentialGroup()
                        .addComponent(Lb_DerniereVisite)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Lb_DerniereVisite_Consult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel_Entreprise2Layout.createSequentialGroup()
                        .addComponent(Lb_RepresentantNomPrenom)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Lb_RepresentantNomPrenom_Consult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel_Entreprise2Layout.setVerticalGroup(
            jPanel_Entreprise2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Entreprise2Layout.createSequentialGroup()
                .addGroup(jPanel_Entreprise2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lb_RepresentantNomPrenom)
                    .addComponent(Lb_RepresentantNomPrenom_Consult, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_Entreprise2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lb_DerniereVisite)
                    .addComponent(Lb_DerniereVisite_Consult, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gauthier_matthieu/image/logo-02.png"))); // NOI18N

        Lb_copyright.setBackground(new java.awt.Color(255, 255, 255));
        Lb_copyright.setFont(new java.awt.Font("Gill Sans MT", 1, 10)); // NOI18N
        Lb_copyright.setForeground(new java.awt.Color(153, 153, 153));
        Lb_copyright.setText("Création Software SSII MGc all rights reserved 2016");

        Lb_NumeroProspect.setFont(new java.awt.Font("Gill Sans MT", 3, 24)); // NOI18N
        Lb_NumeroProspect.setForeground(new java.awt.Color(51, 51, 51));
        Lb_NumeroProspect.setText("*");
        Lb_NumeroProspect.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout jPanel_ConsutationProspectLayout = new javax.swing.GroupLayout(jPanel_ConsutationProspect);
        jPanel_ConsutationProspect.setLayout(jPanel_ConsutationProspectLayout);
        jPanel_ConsutationProspectLayout.setHorizontalGroup(
            jPanel_ConsutationProspectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ConsutationProspectLayout.createSequentialGroup()
                .addGroup(jPanel_ConsutationProspectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_ConsutationProspectLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Lb_copyright, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_ConsutationProspectLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel_ConsutationProspectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel_Entreprise, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE)
                            .addComponent(Lb_Fenetre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel_ConsutationProspectLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel_ConsutationProspectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel_Adresse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel_Entreprise2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_ConsutationProspectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_ConsutationProspectLayout.createSequentialGroup()
                        .addGap(0, 61, Short.MAX_VALUE)
                        .addGroup(jPanel_ConsutationProspectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(logo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_ConsutationProspectLayout.createSequentialGroup()
                                .addComponent(Bt_Imprimer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Bt_Annuler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Bt_Aide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel_Contact, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel_ConsutationProspectLayout.createSequentialGroup()
                        .addComponent(Lb_NumeroProspect, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel_ConsutationProspectLayout.setVerticalGroup(
            jPanel_ConsutationProspectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ConsutationProspectLayout.createSequentialGroup()
                .addGroup(jPanel_ConsutationProspectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lb_Fenetre, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lb_NumeroProspect, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_ConsutationProspectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_ConsutationProspectLayout.createSequentialGroup()
                        .addComponent(jPanel_Entreprise, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jPanel_Adresse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jPanel_Entreprise2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                        .addComponent(Lb_copyright, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_ConsutationProspectLayout.createSequentialGroup()
                        .addComponent(jPanel_Contact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(logo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel_ConsutationProspectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                            .addComponent(Bt_Annuler, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Bt_Aide, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Bt_Imprimer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_ConsutationProspect, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_ConsutationProspect, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Bt_ImprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_ImprimerActionPerformed
        MPanelPrinter fiche = new MPanelPrinter(jPanel_ConsutationProspect);
        fiche.initPrintablePanel();
        fiche.print();
    }//GEN-LAST:event_Bt_ImprimerActionPerformed

    private void Bt_AideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_AideActionPerformed
        JOptionPane.showMessageDialog(null, "Cliquez sur \"Valider\" ou sur \"Annuler\" \n Pour plus d'information, "
            + "contacter le SAV au 06/0010020 \n"
            + "ou sur info@toutbois.fr", "Aide", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_Bt_AideActionPerformed

    private void Bt_AnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_AnnulerActionPerformed
    gp.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_Bt_AnnulerActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
    gp.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_formWindowClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bt_Aide;
    private javax.swing.JButton Bt_Annuler;
    private javax.swing.JButton Bt_Imprimer;
    private javax.swing.JLabel Lb_CodePostal;
    private javax.swing.JLabel Lb_Complement;
    private javax.swing.JLabel Lb_Complement_Consult;
    private javax.swing.JLabel Lb_DerniereVisite;
    private javax.swing.JLabel Lb_DerniereVisite_Consult;
    private javax.swing.JLabel Lb_Fenetre;
    private javax.swing.JLabel Lb_Mail;
    private javax.swing.JLabel Lb_Mail_Consult;
    private javax.swing.JLabel Lb_NomContact;
    private javax.swing.JLabel Lb_NomContact_Consult;
    private javax.swing.JLabel Lb_NumRue;
    private javax.swing.JLabel Lb_NumRue_Consult;
    private javax.swing.JLabel Lb_NumeroProspect;
    private javax.swing.JLabel Lb_Pays;
    private javax.swing.JLabel Lb_Pays_Consult;
    private javax.swing.JLabel Lb_PrenomContact;
    private javax.swing.JLabel Lb_PrenomContact_Consult;
    private javax.swing.JLabel Lb_RepresentantNomPrenom;
    private javax.swing.JLabel Lb_RepresentantNomPrenom_Consult;
    private javax.swing.JLabel Lb_Rue;
    private javax.swing.JLabel Lb_Rue_Consult;
    private javax.swing.JLabel Lb_Siret;
    private javax.swing.JLabel Lb_Siret_Consult;
    private javax.swing.JLabel Lb_Societe;
    private javax.swing.JLabel Lb_Societe_Consult;
    private javax.swing.JLabel Lb_Telephone;
    private javax.swing.JLabel Lb_Telephone_Consult;
    private javax.swing.JLabel Lb_Ville;
    private javax.swing.JLabel Lb_Ville_Consult;
    private javax.swing.JLabel Lb_codePostal_Consult;
    private java.awt.Label Lb_copyright;
    private javax.swing.JPanel jPanel_Adresse;
    private javax.swing.JPanel jPanel_ConsutationProspect;
    private javax.swing.JPanel jPanel_Contact;
    private javax.swing.JPanel jPanel_Entreprise;
    private javax.swing.JPanel jPanel_Entreprise2;
    private javax.swing.JLabel logo;
    // End of variables declaration//GEN-END:variables

    

    

}
