/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gauthier_matthieu.application;


import com.gauthier_matthieu.fonctions.MPanelPrinter;

import java.awt.*;

import java.awt.print.Printable;

import javax.swing.*;
import java.io.*;



/**
 *
 * @author glantoine
 */
public class Consultation_Client extends javax.swing.JFrame {

    private JTable tableau;
    //transmition tableau dans constructeur
    public Consultation_Client(JTable tableau) {
        initComponents();
        setLocationRelativeTo(null);
        this.tableau=tableau;
        
        
        Lb_Complement_Consult.setText("");
        Lb_DerniereCommande_Consult.setText("");
        Lb_Mail_Consult.setText("");
        Lb_NomContact_Consult.setText("");
        Lb_NombreCommande_Consult.setText("");
        Lb_NumRue_Consult.setText("");
        Lb_Pays_Consult.setText("");
        Lb_RepresentantNomPrenom_Consult.setText("");
        Lb_PrenomContact_Consult.setText("");
        Lb_Rue_Consult.setText("");
        Lb_Siret_Consult.setText("");
        Lb_Societe_Consult.setText("");
        Lb_Telephone_Consult.setText("");
        Lb_Ville_Consult.setText("");
        Lb_codePostal_Consult.setText("");
        
            try {
                    InputStream ips = new FileInputStream("Clients.txt");
                    InputStreamReader ipsr = new InputStreamReader(ips,"UTF-8");
                    try (BufferedReader br = new BufferedReader(ipsr)) {

                        String ligne;
                        String[] decompose;
                        //parcours toutes les lignes du fichier Clients.txt
                        while ((ligne = br.readLine()) != null)
                        {
                            //décompose une ligne du fichier Clients.txt en 
                            decompose=ligne.split(";");
                            Lb_NomContact_Consult.setText(tableau.getValueAt(tableau.getSelectedRow(), 0).toString());
                            Lb_PrenomContact_Consult.setText(tableau.getValueAt(tableau.getSelectedRow(), 1).toString());
                            Lb_Societe_Consult.setText(tableau.getValueAt(tableau.getSelectedRow(), 2).toString());
                            Lb_Rue_Consult.setText(tableau.getValueAt(tableau.getSelectedRow(), 3).toString());
                            Lb_Ville_Consult.setText(tableau.getValueAt(tableau.getSelectedRow(), 4).toString());
                            Lb_Mail_Consult.setText(tableau.getValueAt(tableau.getSelectedRow(), 5).toString());
                            Lb_Telephone_Consult.setText(tableau.getValueAt(tableau.getSelectedRow(), 6).toString());
                            Lb_Pays_Consult.setText(tableau.getValueAt(tableau.getSelectedRow(), 7).toString());
                            Lb_codePostal_Consult.setText(tableau.getValueAt(tableau.getSelectedRow(), 8).toString());
                            Lb_Siret_Consult.setText(tableau.getValueAt(tableau.getSelectedRow(), 9).toString());
                            Lb_NombreCommande_Consult.setText(tableau.getValueAt(tableau.getSelectedRow(), 10).toString());
                            Lb_RepresentantNomPrenom_Consult.setText(tableau.getValueAt(tableau.getSelectedRow(), 11).toString());
                            
                            
                            Lb_NumRue_Consult.setText(tableau.getValueAt(tableau.getSelectedRow(), 8).toString());
                            
                            Lb_DerniereCommande_Consult.setText(tableau.getValueAt(tableau.getSelectedRow(), 8).toString());
                            Lb_Complement_Consult.setText(tableau.getValueAt(tableau.getSelectedRow(), 8).toString());
                        }
                    }
                }     
        catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getLocalizedMessage(), "Erreur Jtable", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_ConsutationClients = new javax.swing.JPanel();
        Lb_Fenetre = new javax.swing.JLabel();
        Bt_Annuler = new javax.swing.JButton();
        Bt_Aide = new javax.swing.JButton();
        Bt_Imprimer = new javax.swing.JButton();
        jPanel_Commande = new javax.swing.JPanel();
        Lb_NombreCommande = new javax.swing.JLabel();
        Lb_DerniereCommande = new javax.swing.JLabel();
        Lb_NombreCommande_Consult = new javax.swing.JLabel();
        Lb_DerniereCommande_Consult = new javax.swing.JLabel();
        jPanel_Contact = new javax.swing.JPanel();
        Lb_NomContact = new javax.swing.JLabel();
        Lb_PrenomContact = new javax.swing.JLabel();
        Lb_Mail = new javax.swing.JLabel();
        Lb_Telephone = new javax.swing.JLabel();
        Lb_NomContact_Consult = new javax.swing.JLabel();
        Lb_PrenomContact_Consult = new javax.swing.JLabel();
        Lb_Telephone_Consult = new javax.swing.JLabel();
        Lb_Mail_Consult = new javax.swing.JLabel();
        jPanel_Adresse = new javax.swing.JPanel();
        Lb_Ville = new javax.swing.JLabel();
        Lb_CodePostal = new javax.swing.JLabel();
        Lb_Pays = new javax.swing.JLabel();
        Lb_Pays_Consult = new javax.swing.JLabel();
        Lb_Rue = new javax.swing.JLabel();
        Lb_NumRue = new javax.swing.JLabel();
        Lb_Complement = new javax.swing.JLabel();
        Lb_Rue_Consult = new javax.swing.JLabel();
        Lb_NumRue_Consult = new javax.swing.JLabel();
        Lb_codePostal_Consult = new javax.swing.JLabel();
        Lb_Complement_Consult = new javax.swing.JLabel();
        Lb_Ville_Consult = new javax.swing.JLabel();
        jPanel_Entreprise = new javax.swing.JPanel();
        Lb_Societe = new javax.swing.JLabel();
        Lb_Siret = new javax.swing.JLabel();
        Lb_Societe_Consult = new javax.swing.JLabel();
        Lb_Siret_Consult = new javax.swing.JLabel();
        jPanel_Entreprise2 = new javax.swing.JPanel();
        Lb_RepresentantNomPrenom = new javax.swing.JLabel();
        Lb_RepresentantNomPrenom_Consult = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        Lb_copyright = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Consultation Clients");
        setName("Création Client"); // NOI18N
        setPreferredSize(new java.awt.Dimension(975, 550));
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));

        jPanel_ConsutationClients.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_ConsutationClients.setMaximumSize(new java.awt.Dimension(950, 640));
        jPanel_ConsutationClients.setMinimumSize(new java.awt.Dimension(950, 640));
        jPanel_ConsutationClients.setPreferredSize(new java.awt.Dimension(950, 500));

        Lb_Fenetre.setFont(new java.awt.Font("Gill Sans MT", 3, 30)); // NOI18N
        Lb_Fenetre.setForeground(new java.awt.Color(102, 102, 102));
        Lb_Fenetre.setText("CONSULTATION CLIENTS");
        Lb_Fenetre.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        Bt_Annuler.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Bt_Annuler.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gauthier_matthieu/image/cross-circular-button.png"))); // NOI18N
        Bt_Annuler.setText("QUITTER");
        Bt_Annuler.setPreferredSize(new java.awt.Dimension(130, 25));
        Bt_Annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_AnnulerActionPerformed(evt);
            }
        });

        Bt_Aide.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Bt_Aide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gauthier_matthieu/image/question-mark.png"))); // NOI18N
        Bt_Aide.setText("AIDE");
        Bt_Aide.setPreferredSize(new java.awt.Dimension(130, 25));
        Bt_Aide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_AideActionPerformed(evt);
            }
        });

        Bt_Imprimer.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Bt_Imprimer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gauthier_matthieu/image/printer (1).png"))); // NOI18N
        Bt_Imprimer.setText("IMPRESSION");
        Bt_Imprimer.setToolTipText("");
        Bt_Imprimer.setPreferredSize(new java.awt.Dimension(130, 25));
        Bt_Imprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_ImprimerActionPerformed(evt);
            }
        });

        jPanel_Commande.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_Commande.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "COMMANDE", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Gill Sans MT Condensed", 2, 24), new java.awt.Color(102, 102, 102))); // NOI18N

        Lb_NombreCommande.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        Lb_NombreCommande.setForeground(new java.awt.Color(102, 102, 102));
        Lb_NombreCommande.setText("Nombre de commande :");

        Lb_DerniereCommande.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        Lb_DerniereCommande.setForeground(new java.awt.Color(102, 102, 102));
        Lb_DerniereCommande.setText("Dernière commande :");

        Lb_NombreCommande_Consult.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        Lb_NombreCommande_Consult.setForeground(new java.awt.Color(102, 102, 102));
        Lb_NombreCommande_Consult.setText("zzzzz");

        Lb_DerniereCommande_Consult.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        Lb_DerniereCommande_Consult.setForeground(new java.awt.Color(102, 102, 102));
        Lb_DerniereCommande_Consult.setText("zzzzz");

        javax.swing.GroupLayout jPanel_CommandeLayout = new javax.swing.GroupLayout(jPanel_Commande);
        jPanel_Commande.setLayout(jPanel_CommandeLayout);
        jPanel_CommandeLayout.setHorizontalGroup(
            jPanel_CommandeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_CommandeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_CommandeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Lb_NombreCommande)
                    .addComponent(Lb_DerniereCommande))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel_CommandeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Lb_DerniereCommande_Consult, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lb_NombreCommande_Consult, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel_CommandeLayout.setVerticalGroup(
            jPanel_CommandeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_CommandeLayout.createSequentialGroup()
                .addGroup(jPanel_CommandeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lb_NombreCommande)
                    .addComponent(Lb_NombreCommande_Consult, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_CommandeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Lb_DerniereCommande)
                    .addComponent(Lb_DerniereCommande_Consult, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel_Contact.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_Contact.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CONTACT", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Gill Sans MT Condensed", 2, 24), new java.awt.Color(102, 102, 102))); // NOI18N

        Lb_NomContact.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        Lb_NomContact.setForeground(new java.awt.Color(102, 102, 102));
        Lb_NomContact.setText("Nom :");

        Lb_PrenomContact.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        Lb_PrenomContact.setForeground(new java.awt.Color(102, 102, 102));
        Lb_PrenomContact.setText("Prénom :");

        Lb_Mail.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        Lb_Mail.setForeground(new java.awt.Color(102, 102, 102));
        Lb_Mail.setText("Mail :");

        Lb_Telephone.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        Lb_Telephone.setForeground(new java.awt.Color(102, 102, 102));
        Lb_Telephone.setText("Téléphone :");
        Lb_Telephone.setToolTipText("");

        Lb_NomContact_Consult.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        Lb_NomContact_Consult.setForeground(new java.awt.Color(102, 102, 102));
        Lb_NomContact_Consult.setText("zzzz");
        Lb_NomContact_Consult.setToolTipText("");

        Lb_PrenomContact_Consult.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        Lb_PrenomContact_Consult.setForeground(new java.awt.Color(102, 102, 102));
        Lb_PrenomContact_Consult.setText("zzzz");
        Lb_PrenomContact_Consult.setToolTipText("");

        Lb_Telephone_Consult.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        Lb_Telephone_Consult.setForeground(new java.awt.Color(102, 102, 102));
        Lb_Telephone_Consult.setText("zzzz");
        Lb_Telephone_Consult.setToolTipText("");

        Lb_Mail_Consult.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        Lb_Mail_Consult.setForeground(new java.awt.Color(102, 102, 102));
        Lb_Mail_Consult.setText("zzzz");
        Lb_Mail_Consult.setToolTipText("");

        javax.swing.GroupLayout jPanel_ContactLayout = new javax.swing.GroupLayout(jPanel_Contact);
        jPanel_Contact.setLayout(jPanel_ContactLayout);
        jPanel_ContactLayout.setHorizontalGroup(
            jPanel_ContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ContactLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_ContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Lb_Mail)
                    .addComponent(Lb_Telephone)
                    .addComponent(Lb_NomContact)
                    .addComponent(Lb_PrenomContact))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_ContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Lb_NomContact_Consult, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lb_PrenomContact_Consult, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lb_Telephone_Consult, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lb_Mail_Consult, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel_ContactLayout.setVerticalGroup(
            jPanel_ContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ContactLayout.createSequentialGroup()
                .addGroup(jPanel_ContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lb_NomContact)
                    .addComponent(Lb_NomContact_Consult))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_ContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lb_PrenomContact)
                    .addComponent(Lb_PrenomContact_Consult))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_ContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lb_Telephone)
                    .addComponent(Lb_Telephone_Consult))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_ContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lb_Mail)
                    .addComponent(Lb_Mail_Consult)))
        );

        jPanel_Adresse.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_Adresse.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ADRESSE", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Gill Sans MT Condensed", 2, 24), new java.awt.Color(102, 102, 102))); // NOI18N

        Lb_Ville.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        Lb_Ville.setForeground(new java.awt.Color(102, 102, 102));
        Lb_Ville.setText("Ville :");

        Lb_CodePostal.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        Lb_CodePostal.setForeground(new java.awt.Color(102, 102, 102));
        Lb_CodePostal.setText("Code Postal :");

        Lb_Pays.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        Lb_Pays.setForeground(new java.awt.Color(102, 102, 102));
        Lb_Pays.setText("Pays :");

        Lb_Pays_Consult.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        Lb_Pays_Consult.setForeground(new java.awt.Color(102, 102, 102));
        Lb_Pays_Consult.setText("zzzzz");

        Lb_Rue.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        Lb_Rue.setForeground(new java.awt.Color(102, 102, 102));
        Lb_Rue.setText("Adresse :");

        Lb_NumRue.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        Lb_NumRue.setForeground(new java.awt.Color(102, 102, 102));
        Lb_NumRue.setText("Numéro :");

        Lb_Complement.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        Lb_Complement.setForeground(new java.awt.Color(102, 102, 102));
        Lb_Complement.setText("Complement :");

        Lb_Rue_Consult.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        Lb_Rue_Consult.setForeground(new java.awt.Color(102, 102, 102));
        Lb_Rue_Consult.setText("zzzz");

        Lb_NumRue_Consult.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        Lb_NumRue_Consult.setForeground(new java.awt.Color(102, 102, 102));
        Lb_NumRue_Consult.setText("zzzz");

        Lb_codePostal_Consult.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        Lb_codePostal_Consult.setForeground(new java.awt.Color(102, 102, 102));
        Lb_codePostal_Consult.setText("zzzz");

        Lb_Complement_Consult.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        Lb_Complement_Consult.setForeground(new java.awt.Color(102, 102, 102));
        Lb_Complement_Consult.setText("zzzz");

        Lb_Ville_Consult.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        Lb_Ville_Consult.setForeground(new java.awt.Color(102, 102, 102));
        Lb_Ville_Consult.setText("zzzz");

        javax.swing.GroupLayout jPanel_AdresseLayout = new javax.swing.GroupLayout(jPanel_Adresse);
        jPanel_Adresse.setLayout(jPanel_AdresseLayout);
        jPanel_AdresseLayout.setHorizontalGroup(
            jPanel_AdresseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_AdresseLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_AdresseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_AdresseLayout.createSequentialGroup()
                        .addComponent(Lb_Ville)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Lb_CodePostal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Lb_codePostal_Consult, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel_AdresseLayout.createSequentialGroup()
                        .addGroup(jPanel_AdresseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Lb_Complement)
                            .addComponent(Lb_NumRue))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel_AdresseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_AdresseLayout.createSequentialGroup()
                                .addComponent(Lb_NumRue_Consult, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Lb_Rue)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel_AdresseLayout.createSequentialGroup()
                                .addComponent(Lb_Complement_Consult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())))))
            .addGroup(jPanel_AdresseLayout.createSequentialGroup()
                .addGroup(jPanel_AdresseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_AdresseLayout.createSequentialGroup()
                        .addContainerGap(206, Short.MAX_VALUE)
                        .addComponent(Lb_Rue_Consult, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_AdresseLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(Lb_Pays)
                        .addGap(58, 58, 58)
                        .addGroup(jPanel_AdresseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Lb_Pays_Consult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel_AdresseLayout.createSequentialGroup()
                                .addComponent(Lb_Ville_Consult, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel_AdresseLayout.setVerticalGroup(
            jPanel_AdresseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_AdresseLayout.createSequentialGroup()
                .addGroup(jPanel_AdresseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lb_NumRue)
                    .addComponent(Lb_NumRue_Consult)
                    .addComponent(Lb_Rue)
                    .addComponent(Lb_Rue_Consult))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_AdresseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Lb_Complement_Consult)
                    .addComponent(Lb_Complement))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_AdresseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_AdresseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Lb_Ville_Consult)
                        .addComponent(Lb_CodePostal)
                        .addComponent(Lb_codePostal_Consult))
                    .addComponent(Lb_Ville))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_AdresseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lb_Pays)
                    .addComponent(Lb_Pays_Consult, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel_Entreprise.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_Entreprise.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ENTREPRISE", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Gill Sans MT Condensed", 2, 24), new java.awt.Color(102, 102, 102))); // NOI18N
        jPanel_Entreprise.setPreferredSize(new java.awt.Dimension(114, 111));

        Lb_Societe.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        Lb_Societe.setForeground(new java.awt.Color(102, 102, 102));
        Lb_Societe.setText("Société : ");

        Lb_Siret.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        Lb_Siret.setForeground(new java.awt.Color(102, 102, 102));
        Lb_Siret.setText("Siret : ");

        Lb_Societe_Consult.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        Lb_Societe_Consult.setForeground(new java.awt.Color(102, 102, 102));
        Lb_Societe_Consult.setText("zzz");

        Lb_Siret_Consult.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        Lb_Siret_Consult.setForeground(new java.awt.Color(102, 102, 102));
        Lb_Siret_Consult.setText("zzzzz");

        javax.swing.GroupLayout jPanel_EntrepriseLayout = new javax.swing.GroupLayout(jPanel_Entreprise);
        jPanel_Entreprise.setLayout(jPanel_EntrepriseLayout);
        jPanel_EntrepriseLayout.setHorizontalGroup(
            jPanel_EntrepriseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_EntrepriseLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_EntrepriseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Lb_Societe)
                    .addComponent(Lb_Siret))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_EntrepriseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Lb_Societe_Consult, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Lb_Siret_Consult, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel_EntrepriseLayout.setVerticalGroup(
            jPanel_EntrepriseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_EntrepriseLayout.createSequentialGroup()
                .addGroup(jPanel_EntrepriseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lb_Societe)
                    .addComponent(Lb_Societe_Consult))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_EntrepriseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lb_Siret)
                    .addComponent(Lb_Siret_Consult))
                .addGap(12, 12, 12))
        );

        jPanel_Entreprise2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_Entreprise2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "REPRESENTANT", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Gill Sans MT Condensed", 2, 24), new java.awt.Color(102, 102, 102))); // NOI18N

        Lb_RepresentantNomPrenom.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        Lb_RepresentantNomPrenom.setForeground(new java.awt.Color(102, 102, 102));
        Lb_RepresentantNomPrenom.setText("Nom, Prénom :");

        Lb_RepresentantNomPrenom_Consult.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        Lb_RepresentantNomPrenom_Consult.setForeground(new java.awt.Color(102, 102, 102));
        Lb_RepresentantNomPrenom_Consult.setText("zzzzz");

        javax.swing.GroupLayout jPanel_Entreprise2Layout = new javax.swing.GroupLayout(jPanel_Entreprise2);
        jPanel_Entreprise2.setLayout(jPanel_Entreprise2Layout);
        jPanel_Entreprise2Layout.setHorizontalGroup(
            jPanel_Entreprise2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_Entreprise2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(Lb_RepresentantNomPrenom)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Lb_RepresentantNomPrenom_Consult, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel_Entreprise2Layout.setVerticalGroup(
            jPanel_Entreprise2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Entreprise2Layout.createSequentialGroup()
                .addGroup(jPanel_Entreprise2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lb_RepresentantNomPrenom)
                    .addComponent(Lb_RepresentantNomPrenom_Consult, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gauthier_matthieu/image/logo-02.png"))); // NOI18N

        Lb_copyright.setBackground(new java.awt.Color(255, 255, 255));
        Lb_copyright.setFont(new java.awt.Font("Gill Sans MT", 1, 10)); // NOI18N
        Lb_copyright.setForeground(new java.awt.Color(153, 153, 153));
        Lb_copyright.setText("Création Software SSII MGc all rights reserved 2016");

        javax.swing.GroupLayout jPanel_ConsutationClientsLayout = new javax.swing.GroupLayout(jPanel_ConsutationClients);
        jPanel_ConsutationClients.setLayout(jPanel_ConsutationClientsLayout);
        jPanel_ConsutationClientsLayout.setHorizontalGroup(
            jPanel_ConsutationClientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ConsutationClientsLayout.createSequentialGroup()
                .addGroup(jPanel_ConsutationClientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_ConsutationClientsLayout.createSequentialGroup()
                        .addGroup(jPanel_ConsutationClientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_ConsutationClientsLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jPanel_Entreprise, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel_ConsutationClientsLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel_Adresse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel_ConsutationClientsLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel_ConsutationClientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel_Commande, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Lb_copyright, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                        .addGroup(jPanel_ConsutationClientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_ConsutationClientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPanel_Contact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jPanel_Entreprise2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(logo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_ConsutationClientsLayout.createSequentialGroup()
                                .addComponent(Bt_Imprimer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Bt_Annuler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Bt_Aide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel_ConsutationClientsLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(Lb_Fenetre, javax.swing.GroupLayout.PREFERRED_SIZE, 606, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel_ConsutationClientsLayout.setVerticalGroup(
            jPanel_ConsutationClientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ConsutationClientsLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(Lb_Fenetre, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_ConsutationClientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_ConsutationClientsLayout.createSequentialGroup()
                        .addComponent(jPanel_Entreprise, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel_Adresse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel_Commande, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(Lb_copyright, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_ConsutationClientsLayout.createSequentialGroup()
                        .addComponent(jPanel_Contact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel_Entreprise2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(logo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel_ConsutationClientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                            .addComponent(Bt_Annuler, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Bt_Aide, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Bt_Imprimer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel_ConsutationClients, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel_ConsutationClients, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Bt_AnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_AnnulerActionPerformed
        this.dispose();
    }//GEN-LAST:event_Bt_AnnulerActionPerformed

    private void Bt_AideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_AideActionPerformed
        JOptionPane.showMessageDialog(null, "Cliquez sur \"Valider\" ou sur \"Annuler\" \n Pour plus d'information, "
                + "contacter le SAV au 06/0010020 \n"
                + "ou sur info@toutbois.fr", "Aide", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_Bt_AideActionPerformed

    private void Bt_ImprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_ImprimerActionPerformed
        MPanelPrinter fiche = new MPanelPrinter(jPanel_ConsutationClients);
       
        fiche.print();       
    }//GEN-LAST:event_Bt_ImprimerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bt_Aide;
    private javax.swing.JButton Bt_Annuler;
    private javax.swing.JButton Bt_Imprimer;
    private javax.swing.JLabel Lb_CodePostal;
    private javax.swing.JLabel Lb_Complement;
    private javax.swing.JLabel Lb_Complement_Consult;
    private javax.swing.JLabel Lb_DerniereCommande;
    private javax.swing.JLabel Lb_DerniereCommande_Consult;
    private javax.swing.JLabel Lb_Fenetre;
    private javax.swing.JLabel Lb_Mail;
    private javax.swing.JLabel Lb_Mail_Consult;
    private javax.swing.JLabel Lb_NomContact;
    private javax.swing.JLabel Lb_NomContact_Consult;
    private javax.swing.JLabel Lb_NombreCommande;
    private javax.swing.JLabel Lb_NombreCommande_Consult;
    private javax.swing.JLabel Lb_NumRue;
    private javax.swing.JLabel Lb_NumRue_Consult;
    private javax.swing.JLabel Lb_Pays;
    private javax.swing.JLabel Lb_Pays_Consult;
    private javax.swing.JLabel Lb_PrenomContact;
    private javax.swing.JLabel Lb_PrenomContact_Consult;
    private javax.swing.JLabel Lb_RepresentantNomPrenom;
    private javax.swing.JLabel Lb_RepresentantNomPrenom_Consult;
    private javax.swing.JLabel Lb_Rue;
    private javax.swing.JLabel Lb_Rue_Consult;
    private javax.swing.JLabel Lb_Siret;
    private javax.swing.JLabel Lb_Siret_Consult;
    private javax.swing.JLabel Lb_Societe;
    private javax.swing.JLabel Lb_Societe_Consult;
    private javax.swing.JLabel Lb_Telephone;
    private javax.swing.JLabel Lb_Telephone_Consult;
    private javax.swing.JLabel Lb_Ville;
    private javax.swing.JLabel Lb_Ville_Consult;
    private javax.swing.JLabel Lb_codePostal_Consult;
    private java.awt.Label Lb_copyright;
    private javax.swing.JPanel jPanel_Adresse;
    private javax.swing.JPanel jPanel_Commande;
    private javax.swing.JPanel jPanel_ConsutationClients;
    private javax.swing.JPanel jPanel_Contact;
    private javax.swing.JPanel jPanel_Entreprise;
    private javax.swing.JPanel jPanel_Entreprise2;
    private javax.swing.JLabel logo;
    // End of variables declaration//GEN-END:variables

    

    

}
