/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gauthier_matthieu.application;

import com.gauthier_matthieu.old.GestionDonnees;
import com.gauthier_matthieu.metier.Prospects;
import com.gauthier_matthieu.entities.*;
import com.gauthier_matthieu.interBDD.RequeteProspect;
import com.gauthier_matthieu.interBDD.RequeteRepresentant;
import com.gauthier_matthieu.metier.Representants;
import java.awt.Color;
import java.awt.Toolkit;
import java.io.*;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.util.HashMap;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author glantoine
 */
public class Modification_Prospect extends javax.swing.JFrame {

    
    GestionDonnees gd = new GestionDonnees();
    
    //private HashMap<Integer,Prospects> prospects= gd.getProspects();
    private Prospects prospectObjet;
    private Representants representantObjet;
    private JTable tableau;
    private Gestion_Prospect gp;
    RequeteRepresentant bddRepresentant= new RequeteRepresentant();
    RequeteProspect bddProspect=new RequeteProspect();
    private Pattern verifNomPrenomVilleAdresse,verifMail,verifSiret,verifNumeroTel,verifCodePostaleNumeroRue;
    private Matcher matcherAdresse, matcherMail, matcherSiret,matcherNumeroTel,matcherCodePostale,
            matcherNumeroRue,matcherNom,matcherPrenom,matcherVille;
            
    
    /**
     * Initialise tous les composants de la fenêtre
     * @param tableau Tableau des prospects de l'écran gestion Prospect
     * @param gc Ecran Gestion_Prospect
     */
    
    
    public Modification_Prospect(JTable tableau,Gestion_Prospect gp) {
        initComponents();
        setLocationRelativeTo(null);
        this.gp=gp;
        this.tableau=tableau;
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("..//image//logo-02.png")));
        
        
        
        
        bddRepresentant.ChargementComboBoxRepresentant(CB_Representant);
        
        try{
        
        this.prospectObjet=bddProspect.rechercheProspects(Integer.parseInt(tableau.getValueAt(tableau.getSelectedRow(), 0).toString()));
        
        TF_NomContact.setText(prospectObjet.getNom());
        TF_PrenomContact.setText(prospectObjet.getPrenom());
        TF_Societe.setText(prospectObjet.getNomEntreprise());
        TF_Siret.setText(prospectObjet.getSiret());
        TF_NumRue.setText(Integer.toString(prospectObjet.getNumeroVoie()));
        TF_Adresse.setText(prospectObjet.getAdresse());
        TF_Complement.setText(prospectObjet.getComplementAdresse());
        TF_Ville.setText(prospectObjet.getVille());
        TF_codePostal.setText(prospectObjet.getCodePostal());
        CB_Pays.setSelectedItem(prospectObjet.getPays());
        TF_Mail.setText(prospectObjet.getMail());
        TF_Telephone.setText(prospectObjet.getNumerotel());
        jD_DerniereVisite.setDate(prospectObjet.getDerniereVisite());
        
        try{
        representantObjet= bddRepresentant.rechercheRepresentant(prospectObjet.getNumeroRepresentant());
        CB_Representant.setSelectedItem(prospectObjet.getNumeroRepresentant()+". "+representantObjet.getPrenom()+" "+representantObjet.getNom());
        }
        catch(NullPointerException ex)
        {
            CB_Representant.setSelectedItem("Sélection");
        }
        
        }
        catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "ERREUR SQL", JOptionPane.ERROR_MESSAGE);
        }
        catch(ParseException ex)
        {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "ERREUR CONVERSION DATE", JOptionPane.ERROR_MESSAGE);
        }
        
    }
    
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jP_ModificationProspects = new javax.swing.JPanel();
        Lb_Fenetre = new javax.swing.JLabel();
        Bt_Valider = new javax.swing.JButton();
        Bt_Annuler = new javax.swing.JButton();
        Bt_Aide = new javax.swing.JButton();
        Lb_ChampsObligatoires = new javax.swing.JLabel();
        jPanel_Contact = new javax.swing.JPanel();
        Lb_NomContact = new javax.swing.JLabel();
        TF_NomContact = new javax.swing.JTextField();
        Lb_PrenomContact = new javax.swing.JLabel();
        TF_PrenomContact = new javax.swing.JTextField();
        TF_Mail = new javax.swing.JTextField();
        Lb_Mail = new javax.swing.JLabel();
        Lb_Telephone = new javax.swing.JLabel();
        TF_Telephone = new javax.swing.JTextField();
        jPanel_Adresse = new javax.swing.JPanel();
        Lb_Ville = new javax.swing.JLabel();
        Lb_CodePostal = new javax.swing.JLabel();
        Lb_Pays = new javax.swing.JLabel();
        Lb_Adresse = new javax.swing.JLabel();
        Lb_NumRue = new javax.swing.JLabel();
        TF_NumRue = new javax.swing.JTextField();
        TF_Complement = new javax.swing.JTextField();
        TF_Ville = new javax.swing.JTextField();
        TF_codePostal = new javax.swing.JTextField();
        Lb_Complement = new javax.swing.JLabel();
        CB_Pays = new javax.swing.JComboBox();
        TF_Adresse = new javax.swing.JTextField();
        jPanel_Entreprise = new javax.swing.JPanel();
        Lb_Societe = new javax.swing.JLabel();
        TF_Societe = new javax.swing.JTextField();
        TF_Siret = new javax.swing.JTextField();
        Lb_Siret = new javax.swing.JLabel();
        jPanel_Representant = new javax.swing.JPanel();
        Lb_RepresentantNomPrenom = new javax.swing.JLabel();
        CB_Representant = new javax.swing.JComboBox();
        Lb_DerniereVisite = new javax.swing.JLabel();
        jD_DerniereVisite = new com.toedter.calendar.JDateChooser();
        logo = new javax.swing.JLabel();
        label1 = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Modification Prospect");
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("..//image//logo-02.png")));
        setName("Création Client"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jP_ModificationProspects.setBackground(new java.awt.Color(255, 255, 255));
        jP_ModificationProspects.setMaximumSize(new java.awt.Dimension(950, 530));
        jP_ModificationProspects.setMinimumSize(new java.awt.Dimension(950, 530));
        jP_ModificationProspects.setPreferredSize(new java.awt.Dimension(950, 530));

        Lb_Fenetre.setFont(new java.awt.Font("Gill Sans MT", 3, 30)); // NOI18N
        Lb_Fenetre.setForeground(new java.awt.Color(102, 102, 102));
        Lb_Fenetre.setText("MODIFICATION PROSPECT");
        Lb_Fenetre.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        Bt_Valider.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Bt_Valider.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gauthier_matthieu/image/icon.png"))); // NOI18N
        Bt_Valider.setText("VALIDER");
        Bt_Valider.setMaximumSize(new java.awt.Dimension(80, 23));
        Bt_Valider.setMinimumSize(new java.awt.Dimension(80, 23));
        Bt_Valider.setPreferredSize(new java.awt.Dimension(130, 25));
        Bt_Valider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_ValiderActionPerformed(evt);
            }
        });

        Bt_Annuler.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Bt_Annuler.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gauthier_matthieu/image/cross-circular-button.png"))); // NOI18N
        Bt_Annuler.setText("ANNULER");
        Bt_Annuler.setMaximumSize(new java.awt.Dimension(130, 25));
        Bt_Annuler.setMinimumSize(new java.awt.Dimension(130, 25));
        Bt_Annuler.setPreferredSize(new java.awt.Dimension(130, 25));
        Bt_Annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_AnnulerActionPerformed(evt);
            }
        });

        Bt_Aide.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Bt_Aide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gauthier_matthieu/image/question-mark.png"))); // NOI18N
        Bt_Aide.setText("AIDE");
        Bt_Aide.setMaximumSize(new java.awt.Dimension(130, 25));
        Bt_Aide.setMinimumSize(new java.awt.Dimension(130, 25));
        Bt_Aide.setPreferredSize(new java.awt.Dimension(130, 25));
        Bt_Aide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_AideActionPerformed(evt);
            }
        });

        Lb_ChampsObligatoires.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        Lb_ChampsObligatoires.setForeground(new java.awt.Color(102, 102, 102));
        Lb_ChampsObligatoires.setText("Les champs précédé d'une étoile (*) sont obligatoires");
        Lb_ChampsObligatoires.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jPanel_Contact.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_Contact.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CONTACT", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Gill Sans MT Condensed", 2, 24), new java.awt.Color(102, 102, 102))); // NOI18N

        Lb_NomContact.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        Lb_NomContact.setForeground(new java.awt.Color(102, 102, 102));
        Lb_NomContact.setText("* Nom :");

        Lb_PrenomContact.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        Lb_PrenomContact.setForeground(new java.awt.Color(102, 102, 102));
        Lb_PrenomContact.setText("* Prénom :");

        TF_Mail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_MailActionPerformed(evt);
            }
        });

        Lb_Mail.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        Lb_Mail.setForeground(new java.awt.Color(102, 102, 102));
        Lb_Mail.setText("Mail :");

        Lb_Telephone.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        Lb_Telephone.setForeground(new java.awt.Color(102, 102, 102));
        Lb_Telephone.setText("Téléphone :");

        TF_Telephone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_TelephoneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_ContactLayout = new javax.swing.GroupLayout(jPanel_Contact);
        jPanel_Contact.setLayout(jPanel_ContactLayout);
        jPanel_ContactLayout.setHorizontalGroup(
            jPanel_ContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ContactLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_ContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_ContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel_ContactLayout.createSequentialGroup()
                            .addGroup(jPanel_ContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Lb_NomContact)
                                .addComponent(Lb_PrenomContact))
                            .addGap(23, 23, 23))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_ContactLayout.createSequentialGroup()
                            .addComponent(Lb_Telephone)
                            .addGap(18, 18, 18)))
                    .addGroup(jPanel_ContactLayout.createSequentialGroup()
                        .addComponent(Lb_Mail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel_ContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(TF_Telephone, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                    .addComponent(TF_PrenomContact, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TF_NomContact, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TF_Mail))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_ContactLayout.setVerticalGroup(
            jPanel_ContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ContactLayout.createSequentialGroup()
                .addGroup(jPanel_ContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lb_NomContact)
                    .addComponent(TF_NomContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_ContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lb_PrenomContact)
                    .addComponent(TF_PrenomContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel_ContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TF_Telephone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lb_Telephone))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_ContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TF_Mail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lb_Mail))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel_Adresse.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_Adresse.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ADRESSE", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Gill Sans MT Condensed", 2, 24), new java.awt.Color(102, 102, 102))); // NOI18N

        Lb_Ville.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        Lb_Ville.setForeground(new java.awt.Color(102, 102, 102));
        Lb_Ville.setText("* Ville :");

        Lb_CodePostal.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        Lb_CodePostal.setForeground(new java.awt.Color(102, 102, 102));
        Lb_CodePostal.setText("* CP :");

        Lb_Pays.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        Lb_Pays.setForeground(new java.awt.Color(102, 102, 102));
        Lb_Pays.setText("* Pays :");

        Lb_Adresse.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        Lb_Adresse.setForeground(new java.awt.Color(102, 102, 102));
        Lb_Adresse.setText("* Adresse :");

        Lb_NumRue.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        Lb_NumRue.setForeground(new java.awt.Color(102, 102, 102));
        Lb_NumRue.setText("* Numéro :");

        Lb_Complement.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        Lb_Complement.setForeground(new java.awt.Color(102, 102, 102));
        Lb_Complement.setText("Complement :");

        CB_Pays.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sélection", "Allemagne", "Autriche", "Belgique", "Bulgarie", "Chypre", "Croatie", "Danemark", "Espagne", "Estonie", "Finlande", "France", "Grèce", "Hongrie", "Irlande", "Italie", "Lettonie", "Lituanie", "Luxembourg", "Malte", "Pays-Bas", "Pologne", "Portugal", "République tchèque", "Roumanie", "Royaume-Uni", "Slovaquie", "Slovénie", "Suède" }));

        javax.swing.GroupLayout jPanel_AdresseLayout = new javax.swing.GroupLayout(jPanel_Adresse);
        jPanel_Adresse.setLayout(jPanel_AdresseLayout);
        jPanel_AdresseLayout.setHorizontalGroup(
            jPanel_AdresseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_AdresseLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_AdresseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Lb_Complement)
                    .addComponent(Lb_NumRue)
                    .addComponent(Lb_Ville)
                    .addComponent(Lb_Pays))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_AdresseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_AdresseLayout.createSequentialGroup()
                        .addComponent(TF_NumRue, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Lb_Adresse)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TF_Adresse, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(TF_Complement)
                    .addGroup(jPanel_AdresseLayout.createSequentialGroup()
                        .addComponent(TF_Ville)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Lb_CodePostal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TF_codePostal, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(CB_Pays, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel_AdresseLayout.setVerticalGroup(
            jPanel_AdresseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_AdresseLayout.createSequentialGroup()
                .addGroup(jPanel_AdresseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lb_NumRue)
                    .addComponent(TF_NumRue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lb_Adresse)
                    .addComponent(TF_Adresse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_AdresseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lb_Complement)
                    .addComponent(TF_Complement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_AdresseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lb_Ville)
                    .addComponent(TF_Ville, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lb_CodePostal)
                    .addComponent(TF_codePostal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_AdresseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CB_Pays, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lb_Pays))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel_Entreprise.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_Entreprise.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ENTREPRISE", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Gill Sans MT Condensed", 2, 24), new java.awt.Color(102, 102, 102))); // NOI18N

        Lb_Societe.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        Lb_Societe.setForeground(new java.awt.Color(102, 102, 102));
        Lb_Societe.setText("* Société : ");

        Lb_Siret.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        Lb_Siret.setForeground(new java.awt.Color(102, 102, 102));
        Lb_Siret.setText("Siret : ");

        javax.swing.GroupLayout jPanel_EntrepriseLayout = new javax.swing.GroupLayout(jPanel_Entreprise);
        jPanel_Entreprise.setLayout(jPanel_EntrepriseLayout);
        jPanel_EntrepriseLayout.setHorizontalGroup(
            jPanel_EntrepriseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_EntrepriseLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_EntrepriseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Lb_Societe)
                    .addComponent(Lb_Siret))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_EntrepriseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TF_Siret)
                    .addComponent(TF_Societe))
                .addContainerGap())
        );
        jPanel_EntrepriseLayout.setVerticalGroup(
            jPanel_EntrepriseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_EntrepriseLayout.createSequentialGroup()
                .addGroup(jPanel_EntrepriseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lb_Societe)
                    .addComponent(TF_Societe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_EntrepriseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TF_Siret, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lb_Siret))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        jPanel_Representant.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_Representant.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "REPRESENTANT", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Gill Sans MT Condensed", 2, 24), new java.awt.Color(102, 102, 102))); // NOI18N

        Lb_RepresentantNomPrenom.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        Lb_RepresentantNomPrenom.setForeground(new java.awt.Color(102, 102, 102));
        Lb_RepresentantNomPrenom.setText("* Nom, Prénom :");

        CB_Representant.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Jean-Marc Delapaie", "Paul Savoure", "Marc Laville", "Paul Personne" }));

        Lb_DerniereVisite.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        Lb_DerniereVisite.setForeground(new java.awt.Color(102, 102, 102));
        Lb_DerniereVisite.setText("* Dernière visite :");

        javax.swing.GroupLayout jPanel_RepresentantLayout = new javax.swing.GroupLayout(jPanel_Representant);
        jPanel_Representant.setLayout(jPanel_RepresentantLayout);
        jPanel_RepresentantLayout.setHorizontalGroup(
            jPanel_RepresentantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_RepresentantLayout.createSequentialGroup()
                .addGroup(jPanel_RepresentantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_RepresentantLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Lb_DerniereVisite))
                    .addGroup(jPanel_RepresentantLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(Lb_RepresentantNomPrenom)))
                .addGap(18, 18, 18)
                .addGroup(jPanel_RepresentantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CB_Representant, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jD_DerniereVisite, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel_RepresentantLayout.setVerticalGroup(
            jPanel_RepresentantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_RepresentantLayout.createSequentialGroup()
                .addGroup(jPanel_RepresentantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lb_RepresentantNomPrenom)
                    .addComponent(CB_Representant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_RepresentantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Lb_DerniereVisite)
                    .addComponent(jD_DerniereVisite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gauthier_matthieu/image/logo-02.png"))); // NOI18N

        label1.setBackground(new java.awt.Color(255, 255, 255));
        label1.setFont(new java.awt.Font("Gill Sans MT", 1, 10)); // NOI18N
        label1.setForeground(new java.awt.Color(153, 153, 153));
        label1.setText("Création Software SSII MGc all rights reserved 2016");

        javax.swing.GroupLayout jP_ModificationProspectsLayout = new javax.swing.GroupLayout(jP_ModificationProspects);
        jP_ModificationProspects.setLayout(jP_ModificationProspectsLayout);
        jP_ModificationProspectsLayout.setHorizontalGroup(
            jP_ModificationProspectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_ModificationProspectsLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(Lb_Fenetre, javax.swing.GroupLayout.PREFERRED_SIZE, 606, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jP_ModificationProspectsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jP_ModificationProspectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jP_ModificationProspectsLayout.createSequentialGroup()
                        .addGroup(jP_ModificationProspectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Lb_ChampsObligatoires, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel_Adresse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel_Entreprise, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel_Representant, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jP_ModificationProspectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jP_ModificationProspectsLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jP_ModificationProspectsLayout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(jPanel_Contact, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_ModificationProspectsLayout.createSequentialGroup()
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Bt_Valider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Bt_Annuler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Bt_Aide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jP_ModificationProspectsLayout.setVerticalGroup(
            jP_ModificationProspectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_ModificationProspectsLayout.createSequentialGroup()
                .addComponent(Lb_Fenetre, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jP_ModificationProspectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jP_ModificationProspectsLayout.createSequentialGroup()
                        .addComponent(jPanel_Entreprise, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jPanel_Adresse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jPanel_Representant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Lb_ChampsObligatoires)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE))
                    .addGroup(jP_ModificationProspectsLayout.createSequentialGroup()
                        .addComponent(jPanel_Contact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(logo)
                        .addGap(43, 43, 43)))
                .addGroup(jP_ModificationProspectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jP_ModificationProspectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(Bt_Aide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jP_ModificationProspectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Bt_Valider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Bt_Annuler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jP_ModificationProspects, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jP_ModificationProspects, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Bt_ValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_ValiderActionPerformed
        try {
            //Réinitialise les couleurs des labels
            Lb_Societe.setForeground(new java.awt.Color(102, 102, 102));
            Lb_Siret.setForeground(new java.awt.Color(102, 102, 102));
            Lb_NumRue.setForeground(new java.awt.Color(102, 102, 102));
            Lb_Adresse.setForeground(new java.awt.Color(102, 102, 102));
            Lb_Ville.setForeground(new java.awt.Color(102, 102, 102));
            Lb_CodePostal.setForeground(new java.awt.Color(102, 102, 102));
            Lb_Pays.setForeground(new java.awt.Color(102, 102, 102));
            Lb_NomContact.setForeground(new java.awt.Color(102, 102, 102));
            Lb_PrenomContact.setForeground(new java.awt.Color(102, 102, 102));
            Lb_Mail.setForeground(new java.awt.Color(102, 102, 102));
            Lb_Telephone.setForeground(new java.awt.Color(102, 102, 102));
            Lb_DerniereVisite.setForeground(new java.awt.Color(102, 102, 102));
            Lb_RepresentantNomPrenom.setForeground(new java.awt.Color(102, 102, 102));
            
            verifNomPrenomVilleAdresse = Pattern.compile("^[\\p{L} .'-]+$");
            verifMail = Pattern.compile("^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@((\\[[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\])|(([a-zA-Z\\-0-9]+\\.)+[a-zA-Z]{2,}))$");
            verifNumeroTel = Pattern.compile("[0-9]{10}");
            verifSiret=Pattern.compile("[0-9]{14}");
            verifCodePostaleNumeroRue=Pattern.compile("[0-9]+");
            
            String Verification="Veuillez remplir correctement le(s) champ(s): "+"\n";
            boolean formulaireMalRempli=false;
            
            if ("".equals(TF_Societe.getText())) {
                Lb_Societe.setForeground(Color.red);
                Verification+="--> Société"+"\n";
                formulaireMalRempli=true;
            }
            matcherSiret = verifSiret.matcher(TF_Siret.getText());
            if (!"".equals(TF_Siret.getText()) &&! matcherSiret.matches()){
                Lb_Siret.setForeground(Color.red);
                Verification+="--> Siret"+"\n";
                formulaireMalRempli=true;
            }
            matcherNumeroRue = verifCodePostaleNumeroRue.matcher(TF_NumRue.getText());
            if ("".equals(TF_NumRue.getText()) &&! matcherNumeroRue.matches()) {
                Lb_NumRue.setForeground(Color.red);
                Verification+="--> Numéro de la rue"+"\n";
                formulaireMalRempli=true;
            }
            matcherAdresse = verifNomPrenomVilleAdresse.matcher(TF_Adresse.getText());
            if ("".equals(TF_Adresse.getText()) &&! matcherAdresse.matches()) {
                Lb_Adresse.setForeground(Color.red);
                Verification+="--> Adresse"+"\n";
                formulaireMalRempli=true;
            }
            matcherVille = verifNomPrenomVilleAdresse.matcher(TF_Ville.getText());
            if ("".equals(TF_Ville.getText()) &&! matcherVille.matches()) {
                Lb_Ville.setForeground(Color.red);
                Verification+="--> Ville"+"\n";
                formulaireMalRempli=true;
            }
            if ("Sélection".equals(CB_Pays.getSelectedItem().toString())) {
                Lb_Pays.setForeground(Color.red);
                Verification+="--> Pays"+"\n";
                formulaireMalRempli=true;
            }
            if ("Sélection".equals(CB_Representant.getSelectedItem().toString())) {
                Lb_RepresentantNomPrenom.setForeground(Color.red);
                Verification+="--> Représentant"+"\n";
                formulaireMalRempli=true;
            }
            matcherCodePostale = verifCodePostaleNumeroRue.matcher(TF_codePostal.getText());
            if ("".equals(TF_codePostal.getText()) &&! matcherCodePostale.matches()) {
                Lb_CodePostal.setForeground(Color.red);
                Verification+="--> Code postal"+"\n";
                formulaireMalRempli=true;
            }
            matcherNom = verifNomPrenomVilleAdresse.matcher(TF_NomContact.getText());
            if ("".equals(TF_NomContact.getText())&&! matcherNom.matches()) {
                Lb_NomContact.setForeground(Color.red);
                Verification+="--> Nom du contact" +"\n";
                formulaireMalRempli=true;
            }
            matcherPrenom = verifNomPrenomVilleAdresse.matcher(TF_PrenomContact.getText());
            if ("".equals(TF_PrenomContact.getText()) &&! matcherPrenom.matches()) {
                Lb_PrenomContact.setForeground(Color.red);
                Verification+="--> Prénom du contact"+"\n";
                formulaireMalRempli=true;
            }
            if (jD_DerniereVisite.getDate()==null) {
                Lb_DerniereVisite.setForeground(Color.red);
                Verification+="--> Date"+"\n";
                formulaireMalRempli=true;
            }
            matcherMail = verifMail.matcher(TF_Mail.getText());
            if (!"".equals(TF_Mail.getText())&& !matcherMail.matches()){
            Lb_Mail.setForeground(Color.red);
            Verification+="--> Mail"+"\n";
            formulaireMalRempli=true;
            }
            matcherNumeroTel = verifNumeroTel.matcher(TF_Telephone.getText());
            if(!"".equals(TF_Telephone.getText()) &&! matcherNumeroTel.matches()){
            Lb_Telephone.setForeground(Color.red);
            Verification+="--> Numéro de téléphone"+"\n";
            formulaireMalRempli=true;
            }

            if (formulaireMalRempli) 
            {                   
                JOptionPane.showMessageDialog(null, Verification, "Attention", JOptionPane.ERROR_MESSAGE);
            } else {
            prospectObjet.setNom(TF_NomContact.getText());
            prospectObjet.setPrenom(TF_PrenomContact.getText());
            prospectObjet.setNomEntreprise(TF_Societe.getText());
            prospectObjet.setAdresse(TF_Adresse.getText());
            prospectObjet.setSiret(TF_Siret.getText());
            prospectObjet.setNumeroVoie(Integer.parseInt(TF_NumRue.getText()));
            prospectObjet.setComplementAdresse(TF_Complement.getText());
            prospectObjet.setVille(TF_Ville.getText());
            prospectObjet.setCodePostal(TF_codePostal.getText());
            prospectObjet.setPays(CB_Pays.getSelectedItem().toString());
            prospectObjet.setMail(TF_Mail.getText());
            prospectObjet.setNumerotel(TF_Telephone.getText());
            prospectObjet.setDerniereVisite(jD_DerniereVisite.getDate());
            
            String[] numeroRepresentant;
            numeroRepresentant=CB_Representant.getSelectedItem().toString().split("\\.");
            prospectObjet.setNumeroRepresentant(Integer.parseInt(numeroRepresentant[0]));
            
            bddProspect.updateBDDProspect(prospectObjet);
              
                dispose();
                gp.setVisible(true);
                JOptionPane.showMessageDialog(null, " Modification du prospect effectuée.", "Information", JOptionPane.INFORMATION_MESSAGE);
            }
             

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Attention", JOptionPane.ERROR_MESSAGE);

        }
        
    }//GEN-LAST:event_Bt_ValiderActionPerformed

    private void Bt_AnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_AnnulerActionPerformed
         //Réaffiche la fenêtre Gestion Client lorsque l'on quitte l'application
        gp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Bt_AnnulerActionPerformed


    private void Bt_AideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_AideActionPerformed
        JOptionPane.showMessageDialog(null, "Cliquez sur \"Valider\" ou sur \"Annuler\" \n Pour plus d'information, "
                + "contacter le SAV au 06/0010020 \n"
                + "ou sur info@toutbois.fr", "Aide", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_Bt_AideActionPerformed

    private void TF_MailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_MailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_MailActionPerformed

    private void TF_TelephoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_TelephoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_TelephoneActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        //Réaffiche la fenêtre Gestion Client lorsque l'on quitte l'application
        gp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        
    }//GEN-LAST:event_formWindowClosed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bt_Aide;
    private javax.swing.JButton Bt_Annuler;
    private javax.swing.JButton Bt_Valider;
    private javax.swing.JComboBox CB_Pays;
    private javax.swing.JComboBox CB_Representant;
    private javax.swing.JLabel Lb_Adresse;
    private javax.swing.JLabel Lb_ChampsObligatoires;
    private javax.swing.JLabel Lb_CodePostal;
    private javax.swing.JLabel Lb_Complement;
    private javax.swing.JLabel Lb_DerniereVisite;
    private javax.swing.JLabel Lb_Fenetre;
    private javax.swing.JLabel Lb_Mail;
    private javax.swing.JLabel Lb_NomContact;
    private javax.swing.JLabel Lb_NumRue;
    private javax.swing.JLabel Lb_Pays;
    private javax.swing.JLabel Lb_PrenomContact;
    private javax.swing.JLabel Lb_RepresentantNomPrenom;
    private javax.swing.JLabel Lb_Siret;
    private javax.swing.JLabel Lb_Societe;
    private javax.swing.JLabel Lb_Telephone;
    private javax.swing.JLabel Lb_Ville;
    private javax.swing.JTextField TF_Adresse;
    private javax.swing.JTextField TF_Complement;
    private javax.swing.JTextField TF_Mail;
    private javax.swing.JTextField TF_NomContact;
    private javax.swing.JTextField TF_NumRue;
    private javax.swing.JTextField TF_PrenomContact;
    private javax.swing.JTextField TF_Siret;
    private javax.swing.JTextField TF_Societe;
    private javax.swing.JTextField TF_Telephone;
    private javax.swing.JTextField TF_Ville;
    private javax.swing.JTextField TF_codePostal;
    private com.toedter.calendar.JDateChooser jD_DerniereVisite;
    private javax.swing.JPanel jP_ModificationProspects;
    private javax.swing.JPanel jPanel_Adresse;
    private javax.swing.JPanel jPanel_Contact;
    private javax.swing.JPanel jPanel_Entreprise;
    private javax.swing.JPanel jPanel_Representant;
    private java.awt.Label label1;
    private javax.swing.JLabel logo;
    // End of variables declaration//GEN-END:variables
}
