/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gauthier_matthieu.application;

import com.gauthier_matthieu.entities.Clients;
import java.awt.Color;
import java.io.*;
import javax.swing.JOptionPane;

/**
 *
 * @author glantoine
 */
public class Nouveau_Prospect extends javax.swing.JFrame {

    public Nouveau_Prospect() {
        initComponents();
        setLocationRelativeTo(null);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Lb_Fenetre = new javax.swing.JLabel();
        Lb_Entreprise = new javax.swing.JLabel();
        Lb_Adresse = new javax.swing.JLabel();
        Lb_Contact = new javax.swing.JLabel();
        Lb_Societe = new javax.swing.JLabel();
        TF_Societe = new javax.swing.JTextField();
        Lb_Siret = new javax.swing.JLabel();
        TF_Siret = new javax.swing.JTextField();
        Lb_NumRue = new javax.swing.JLabel();
        TF_NumRue = new javax.swing.JTextField();
        Lb_Rue = new javax.swing.JLabel();
        TF_Rue = new javax.swing.JTextField();
        Lb_Ville = new javax.swing.JLabel();
        TF_Ville = new javax.swing.JTextField();
        Lb_CodePostal = new javax.swing.JLabel();
        TF_codePostal = new javax.swing.JTextField();
        Lb_Pays = new javax.swing.JLabel();
        TF_Pays = new javax.swing.JTextField();
        Lb_NomContact = new javax.swing.JLabel();
        TF_NomContact = new javax.swing.JTextField();
        Lb_PrenomContact = new javax.swing.JLabel();
        TF_PrenomContact = new javax.swing.JTextField();
        Lb_Telephone = new javax.swing.JLabel();
        TF_Telephone = new javax.swing.JTextField();
        Lb_Mail = new javax.swing.JLabel();
        TF_Mail = new javax.swing.JTextField();
        Bt_Valider = new javax.swing.JButton();
        Bt_Annuler = new javax.swing.JButton();
        Bt_Aide = new javax.swing.JButton();
        Lb_RepresentantNomPrenom = new javax.swing.JLabel();
        Lb_TitreContact1 = new javax.swing.JLabel();
        CB_Representant = new javax.swing.JComboBox<>();
        Lb_ChampsObligatoires = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Création Clients");
        setName("Création Client"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(390, 600));
        jPanel1.setMinimumSize(new java.awt.Dimension(390, 600));
        jPanel1.setPreferredSize(new java.awt.Dimension(390, 600));

        Lb_Fenetre.setFont(new java.awt.Font("Gill Sans MT", 3, 36)); // NOI18N
        Lb_Fenetre.setForeground(new java.awt.Color(102, 102, 102));
        Lb_Fenetre.setText("Création Prospect");
        Lb_Fenetre.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        Lb_Entreprise.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 18)); // NOI18N
        Lb_Entreprise.setForeground(new java.awt.Color(102, 102, 102));
        Lb_Entreprise.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Lb_Entreprise.setText("Entreprise");

        Lb_Adresse.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 18)); // NOI18N
        Lb_Adresse.setForeground(new java.awt.Color(102, 102, 102));
        Lb_Adresse.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Lb_Adresse.setText("Adresse");

        Lb_Contact.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 18)); // NOI18N
        Lb_Contact.setForeground(new java.awt.Color(102, 102, 102));
        Lb_Contact.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Lb_Contact.setText("Contact");

        Lb_Societe.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Lb_Societe.setText("* Société : ");

        Lb_Siret.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Lb_Siret.setText("* Siret : ");

        Lb_NumRue.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Lb_NumRue.setText("* n°");

        Lb_Rue.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Lb_Rue.setText("* Rue :");

        Lb_Ville.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Lb_Ville.setText("* Ville :");

        Lb_CodePostal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Lb_CodePostal.setText("* Code Postal :");

        Lb_Pays.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Lb_Pays.setText("* Pays :");

        Lb_NomContact.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Lb_NomContact.setText("* Nom :");

        Lb_PrenomContact.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Lb_PrenomContact.setText("* Prénom :");

        Lb_Telephone.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Lb_Telephone.setText("Téléphone :");

        TF_Telephone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_TelephoneActionPerformed(evt);
            }
        });

        Lb_Mail.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Lb_Mail.setText("Mail :");

        TF_Mail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_MailActionPerformed(evt);
            }
        });

        Bt_Valider.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Bt_Valider.setText("VALIDER");
        Bt_Valider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_ValiderActionPerformed(evt);
            }
        });

        Bt_Annuler.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Bt_Annuler.setText("ANNULER");
        Bt_Annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_AnnulerActionPerformed(evt);
            }
        });

        Bt_Aide.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Bt_Aide.setText("AIDE");
        Bt_Aide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_AideActionPerformed(evt);
            }
        });

        Lb_RepresentantNomPrenom.setText("Nom, Prénom :");

        Lb_TitreContact1.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 18)); // NOI18N
        Lb_TitreContact1.setForeground(new java.awt.Color(102, 102, 102));
        Lb_TitreContact1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Lb_TitreContact1.setText("Représentant");

        CB_Representant.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CB_Representant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CB_RepresentantActionPerformed(evt);
            }
        });

        Lb_ChampsObligatoires.setText("Les champs précédé d'une étoile (*) sont obligatoires");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(Lb_ChampsObligatoires, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Lb_Fenetre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Bt_Annuler, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Bt_Aide, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Bt_Valider, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Lb_Mail)
                                        .addComponent(Lb_RepresentantNomPrenom))
                                    .addGap(16, 16, 16)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(CB_Representant, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(TF_Mail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Lb_TitreContact1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(Lb_Telephone)
                                    .addGap(30, 30, 30)
                                    .addComponent(TF_Telephone, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(Lb_PrenomContact)
                                    .addGap(35, 35, 35)
                                    .addComponent(TF_PrenomContact, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(Lb_NomContact)
                                    .addGap(50, 50, 50)
                                    .addComponent(TF_NomContact, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Lb_Rue)
                                        .addComponent(Lb_Ville)
                                        .addComponent(Lb_CodePostal)
                                        .addComponent(Lb_Pays))
                                    .addGap(14, 14, 14)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(TF_codePostal, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TF_Ville, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TF_Pays, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Lb_Contact, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(TF_Rue, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(Lb_NumRue)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(TF_NumRue, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(Lb_Siret)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(Lb_Entreprise, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(Lb_Societe)
                                    .addGap(33, 33, 33)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(TF_Societe, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(TF_Siret, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(Lb_Adresse, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(31, 31, 31))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Lb_Fenetre, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Lb_Entreprise)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TF_Societe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lb_Societe))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TF_Siret, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lb_Siret))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Lb_Adresse)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TF_Rue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lb_Rue)
                    .addComponent(Lb_NumRue)
                    .addComponent(TF_NumRue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TF_Ville, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lb_Ville))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TF_codePostal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lb_CodePostal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TF_Pays, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lb_Pays))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Lb_Contact)
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lb_NomContact)
                    .addComponent(TF_NomContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lb_PrenomContact)
                    .addComponent(TF_PrenomContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TF_Telephone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lb_Telephone))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TF_Mail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lb_Mail))
                .addGap(20, 20, 20)
                .addComponent(Lb_TitreContact1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lb_RepresentantNomPrenom)
                    .addComponent(CB_Representant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(Lb_ChampsObligatoires)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Bt_Valider)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bt_Annuler)
                    .addComponent(Bt_Aide))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Bt_ValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_ValiderActionPerformed
        try {

            if ("".equals(TF_Societe.getText())) {
                Lb_Societe.setForeground(Color.red);
            }

            if ("".equals(TF_Siret.getText())) {
                Lb_Siret.setForeground(Color.red);
            }

            if ("".equals(TF_NumRue.getText())) {
                Lb_NumRue.setForeground(Color.red);
            }

            if ("".equals(TF_Rue.getText())) {
                Lb_Rue.setForeground(Color.red);
            }

            if ("".equals(TF_Ville.getText())) {
                Lb_Ville.setForeground(Color.red);
            }

            if ("".equals(TF_codePostal.getText())) {
                Lb_CodePostal.setForeground(Color.red);
            }

            if ("".equals(TF_Pays.getText())) {
                Lb_Pays.setForeground(Color.red);
            }

            if ("".equals(TF_NomContact.getText())) {
                Lb_NomContact.setForeground(Color.red);
            }

            if ("".equals(TF_PrenomContact.getText())) {
                Lb_PrenomContact.setForeground(Color.red);
            }

            if ("".equals(TF_Societe.getText()) || "".equals(TF_Siret.getText()) || "".equals(TF_NumRue.getText()) || "".equals(TF_Rue.getText()) || "".equals(TF_Ville.getText()) || "".equals(TF_codePostal.getText()) || "".equals(TF_Pays.getText()) || "".equals(TF_NomContact.getText()) || "".equals(TF_PrenomContact.getText())) {
                JOptionPane.showMessageDialog(null, "Veuillez remplir", "Attention", JOptionPane.ERROR_MESSAGE);
            } else {

                String chaine1;
                chaine1 = TF_NomContact.getText() + "¤" + TF_PrenomContact.getText() + "¤" + TF_Societe.getText();

                try {
                    File ff = new File("Clients.txt");

                    
                    ff.createNewFile();
                    

                    BufferedWriter ffw = new BufferedWriter(new FileWriter(ff, true));

                    ffw.write(chaine1);
                    ffw.newLine();
                    ffw.close();
                    dispose();
                    
                } catch (IOException ex) {
                    JOptionPane.showMessageDialog(null, ex.getMessage(), "Attention", JOptionPane.ERROR_MESSAGE);
                }
            
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Attention", JOptionPane.ERROR_MESSAGE);

        }
        
    }//GEN-LAST:event_Bt_ValiderActionPerformed

    private void Bt_AnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_AnnulerActionPerformed
        this.dispose();
    }//GEN-LAST:event_Bt_AnnulerActionPerformed


    private void Bt_AideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_AideActionPerformed
        JOptionPane.showMessageDialog(null, "Cliquez sur \"Valider\" ou sur \"Annuler\" \n Pour plus d'information, "
                + "contacter le SAV au 06/0010020 \n"
                + "ou sur info@toutbois.fr", "Aide", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_Bt_AideActionPerformed

    private void TF_MailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_MailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_MailActionPerformed

    private void TF_TelephoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_TelephoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_TelephoneActionPerformed

    private void CB_RepresentantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CB_RepresentantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CB_RepresentantActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bt_Aide;
    private javax.swing.JButton Bt_Annuler;
    private javax.swing.JButton Bt_Valider;
    private javax.swing.JComboBox<String> CB_Representant;
    private javax.swing.JLabel Lb_Adresse;
    private javax.swing.JLabel Lb_ChampsObligatoires;
    private javax.swing.JLabel Lb_CodePostal;
    private javax.swing.JLabel Lb_Contact;
    private javax.swing.JLabel Lb_Entreprise;
    private javax.swing.JLabel Lb_Fenetre;
    private javax.swing.JLabel Lb_Mail;
    private javax.swing.JLabel Lb_NomContact;
    private javax.swing.JLabel Lb_NumRue;
    private javax.swing.JLabel Lb_Pays;
    private javax.swing.JLabel Lb_PrenomContact;
    private javax.swing.JLabel Lb_RepresentantNomPrenom;
    private javax.swing.JLabel Lb_Rue;
    private javax.swing.JLabel Lb_Siret;
    private javax.swing.JLabel Lb_Societe;
    private javax.swing.JLabel Lb_Telephone;
    private javax.swing.JLabel Lb_TitreContact1;
    private javax.swing.JLabel Lb_Ville;
    private javax.swing.JTextField TF_Mail;
    private javax.swing.JTextField TF_NomContact;
    private javax.swing.JTextField TF_NumRue;
    private javax.swing.JTextField TF_Pays;
    private javax.swing.JTextField TF_PrenomContact;
    private javax.swing.JTextField TF_Rue;
    private javax.swing.JTextField TF_Siret;
    private javax.swing.JTextField TF_Societe;
    private javax.swing.JTextField TF_Telephone;
    private javax.swing.JTextField TF_Ville;
    private javax.swing.JTextField TF_codePostal;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
